In [1]:
# hide warnings
import warnings
warnings.filterwarnings('ignore')
# Import Libraries
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set_context("paper", font_scale = 1, rc={"grid.linewidth": 3})
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 400)
from sklearn.linear_model import LogisticRegression,LinearRegression,LassoCV,Lasso
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA,IncrementalPCA
from sklearn.model_selection import GridSearchCV,cross_val_score,KFold,StratifiedKFold
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,precision_score,recall_score
from sklearn.metrics import precision_recall_curve,roc_auc_score,roc_curve
from imblearn.over_sampling import SMOTE,RandomOverSampler

In [2]:
telecom = pd.read_csv('telecom_churn_data.csv')
telecom.head()

mobile_number  circle_id  loc_og_t2o_mou  std_og_t2o_mou  loc_ic_t2o_mou  \
0     7000842753        109             0.0             0.0             0.0   
1     7001865778        109             0.0             0.0             0.0   
2     7001625959        109             0.0             0.0             0.0   
3     7001204172        109             0.0             0.0             0.0   
4     7000142493        109             0.0             0.0             0.0   

  last_date_of_month_6 last_date_of_month_7 last_date_of_month_8  \
0            6/30/2014            7/31/2014            8/31/2014   
1            6/30/2014            7/31/2014            8/31/2014   
2            6/30/2014            7/31/2014            8/31/2014   
3            6/30/2014            7/31/2014            8/31/2014   
4            6/30/2014            7/31/2014            8/31/2014   

  last_date_of_month_9   arpu_6   arpu_7   arpu_8   arpu_9  onnet_mou_6  \
0            9/30/2014  197.385  214.816  213.803   21.100          NaN   
1            9/30/2014   34.047  355.074  268.321   86.285        24.11   
2            9/30/2014  167.690  189.058  210.226  290.714        11.54   
3            9/30/2014  221.338  251.102  508.054  389.500        99.91   
4            9/30/2014  261.636  309.876  238.174  163.426        50.31   

   onnet_mou_7  onnet_mou_8  onnet_mou_9  offnet_mou_6  offnet_mou_7  \
0          NaN         0.00          NaN           NaN           NaN   
1        78.68         7.68        18.34         15.74         99.84   
2        55.24        37.26        74.81        143.33        220.59   
3        54.39       310.98       241.71        123.31        109.01   
4       149.44        83.89        58.78         76.96         91.88   

   offnet_mou_8  offnet_mou_9  roam_ic_mou_6  roam_ic_mou_7  roam_ic_mou_8  \
0          0.00           NaN            NaN            NaN           0.00   
1        304.76         53.76            0.0           0.00           0.00   
2        208.36        118.91            0.0           0.00           0.00   
3         71.68        113.54            0.0          54.86          44.38   
4        124.26         45.81            0.0           0.00           0.00   

   roam_ic_mou_9  roam_og_mou_6  roam_og_mou_7  roam_og_mou_8  roam_og_mou_9  \
0            NaN            NaN            NaN           0.00            NaN   
1           0.00            0.0           0.00           0.00           0.00   
2          38.49            0.0           0.00           0.00          70.94   
3           0.00            0.0          28.09          39.04           0.00   
4           0.00            0.0           0.00           0.00           0.00   

   loc_og_t2t_mou_6  loc_og_t2t_mou_7  loc_og_t2t_mou_8  loc_og_t2t_mou_9  \
0               NaN               NaN              0.00               NaN   
1             23.88             74.56              7.68             18.34   
2              7.19             28.74             13.58             14.39   
3             73.68             34.81             10.61             15.49   
4             50.31            149.44             83.89             58.78   

   loc_og_t2m_mou_6  loc_og_t2m_mou_7  loc_og_t2m_mou_8  loc_og_t2m_mou_9  \
0               NaN               NaN              0.00               NaN   
1             11.51             75.94            291.86             53.76   
2             29.34             16.86             38.46             28.16   
3            107.43             83.21             22.46             65.46   
4             67.64             91.88            124.26             37.89   

   loc_og_t2f_mou_6  loc_og_t2f_mou_7  loc_og_t2f_mou_8  loc_og_t2f_mou_9  \
0               NaN               NaN              0.00               NaN   
1              0.00              0.00              0.00              0.00   
2             24.11             21.79             15.61             22.24   
3              1.91              0.65              

In [3]:
#Checking the shape
print(telecom.shape)
print('\n')
# Checking Dataset Info 
print(telecom.info(verbose=True,null_counts=True))

(99999, 226)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   mobile_number             99999 non-null  int64  
 1   circle_id                 99999 non-null  int64  
 2   loc_og_t2o_mou            98981 non-null  float64
 3   std_og_t2o_mou            98981 non-null  float64
 4   loc_ic_t2o_mou            98981 non-null  float64
 5   last_date_of_month_6      99999 non-null  object 
 6   last_date_of_month_7      99398 non-null  object 
 7   last_date_of_month_8      98899 non-null  object 
 8   last_date_of_month_9      98340 non-null  object 
 9   arpu_6                    99999 non-null  float64
 10  arpu_7                    99999 non-null  float64
 11  arpu_8                    99999 non-null  float64
 12  arpu_9                    99999 non-null  float64
 13  onnet_mou_6               96062 non-null  flo

In [4]:
#Summary and checking outliers
telecom.describe(percentiles=[0.25,0.5,0.75,0.99])

mobile_number  circle_id  loc_og_t2o_mou  std_og_t2o_mou  \
count   9.999900e+04    99999.0         98981.0         98981.0   
mean    7.001207e+09      109.0             0.0             0.0   
std     6.956694e+05        0.0             0.0             0.0   
min     7.000000e+09      109.0             0.0             0.0   
25%     7.000606e+09      109.0             0.0             0.0   
50%     7.001205e+09      109.0             0.0             0.0   
75%     7.001812e+09      109.0             0.0             0.0   
99%     7.002387e+09      109.0             0.0             0.0   
max     7.002411e+09      109.0             0.0             0.0   

       loc_ic_t2o_mou        arpu_6        arpu_7        arpu_8        arpu_9  \
count         98981.0  99999.000000  99999.000000  99999.000000  99999.000000   
mean              0.0    282.987358    278.536648    279.154731    261.645069   
std               0.0    328.439770    338.156291    344.474791    341.998630   
min               0.0  -2258.709000  -2014.045000   -945.808000  -1899.505000   
25%               0.0     93.411500     86.980500     84.126000     62.685000   
50%               0.0    197.704000    191.640000    192.080000    176.849000   
75%               0.0    371.060000    365.344500    369.370500    353.466500   
99%               0.0   1410.792540   1428.685880   1455.539960   1402.445660   
max               0.0  27731.088000  35145.834000  33543.624000  38805.617000   

        onnet_mou_6   onnet_mou_7   onnet_mou_8   onnet_mou_9  offnet_mou_6  \
count  96062.000000  96140.000000  94621.000000  92254.000000  96062.000000   
mean     132.395875    133.670805    133.018098    130.302327    197.935577   
std      297.207406    308.794148    308.951589    308.477668    316.851613   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        7.380000      6.660000      6.460000      5.330000     34.730000   
50%       34.310000     32.330000     32.360000     29.840000     96.310000   
75%      118.740000    115.595000    115.860000    112.130000    231.860000   
99%     1431.760500   1478.533300   1480.334000   1445.766400   1539.535800   
max     7376.710000   8157.780000  10752.560000  10427.460000   8362.360000   

       offnet_mou_7  offnet_mou_8  offnet_mou_9  roam_ic_mou_6  roam_ic_mou_7  \
count  96140.000000  94621.000000  92254.000000   96062.000000   96140.000000   
mean     197.045133    196.574803    190.337222       9.950013       7.149898   
std      325.862803    327.170662    319.396092      72.825411      73.447948   
min        0.000000      0.000000      0.000000       0.000000       0.000000   
25%       32.190000     31.630000     27.130000       0.000000       0.000000   
50%       91.735000     92.140000     87.290000       0.000000       0.000000   
75%      226.815000    228.260000    220.505000       0.000000       0.000000   
99%     1549.379500   1530.398000   1521.328700     219.847000     154.483200   
max     9667.130000  14007.340000  10310.760000   13724.380000   15371.040000   

       roam_ic_mou_8  roam_ic_mou_9  roam_og_mou_6  roam_og_mou_7  \
count   94621.000000   92254.000000   96062.000000   96140.000000   
mean        7.292981       6.343841      13.911337       9.818732   
std        68.402466      57.137537      71.443196      58.455762   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       0.000000   
50%         0.000000       0.000000       0.000000       0.000000   
75%         0.000000       0.000000       0.000000       0.000000   
99%       162.940000     140.983500     285.995800     220.988600   
max     13095.360000    8464.030000    3775.110000    2812.040000   

       roam_og_mou_8  roam_og_mou_9  loc_og_t2t_mou_6  loc_og_t2t_mou_7  \
count   94621.000000   92254.000000      96062.000000      96140.000000   
mean        9.971890       8.555519         47.100763         46.473010   
std    

In [5]:
#Function to check percentage of null values present in dataset 
def calnullpercentage(df):
    missing_num= df[df.columns].isna().sum().sort_values(ascending=False)
    missing_perc= (df[df.columns].isna().sum()/len(df)*100).sort_values(ascending=False)
    missing= pd.concat([missing_num,missing_perc],keys=['Total','Percentage'],axis=1)
    missing= missing[missing['Percentage']>0]
    return missing

In [6]:
# check the %age of null values
calnullpercentage(telecom)


Total  Percentage
count_rech_2g_6           74846   74.846748
date_of_last_rech_data_6  74846   74.846748
count_rech_3g_6           74846   74.846748
av_rech_amt_data_6        74846   74.846748
max_rech_data_6           74846   74.846748
total_rech_data_6         74846   74.846748
arpu_3g_6                 74846   74.846748
arpu_2g_6                 74846   74.846748
night_pck_user_6          74846   74.846748
fb_user_6                 74846   74.846748
arpu_3g_7                 74428   74.428744
count_rech_2g_7           74428   74.428744
fb_user_7                 74428   74.428744
count_rech_3g_7           74428   74.428744
arpu_2g_7                 74428   74.428744
av_rech_amt_data_7        74428   74.428744
max_rech_data_7           74428   74.428744
night_pck_user_7          74428   74.428744
total_rech_data_7         74428   74.428744
date_of_last_rech_data_7  74428   74.428744
night_pck_user_9          74077   74.077741
date_of_last_rech_data_9  74077   74.077741
fb_user_9                 74077   74.077741
arpu_2g_9                 74077   74.077741
max_rech_data_9           74077   74.077741
arpu_3g_9                 74077   74.077741
total_rech_data_9         74077   74.077741
av_rech_amt_data_9        74077   74.077741
count_rech_3g_9           74077   74.077741
count_rech_2g_9           74077   74.077741
fb_user_8                 73660   73.660737
av_rech_amt_data_8        73660   73.660737
count_rech_3g_8           73660   73.660737
count_rech_2g_8           73660   73.660737
date_of_last_rech_data_8  73660   73.660737
total_rech_data_8         73660   73.660737
max_rech_data_8           73660   73.660737
arpu_3g_8                 73660   73.660737
arpu_2g_8                 73660   73.660737
night_pck_user_8          73660   73.660737
std_ic_t2m_mou_9           7745    7.745077
spl_ic_mou_9               7745    7.745077
loc_ic_mou_9               7745    7.745077
isd_ic_mou_9               7745    7.745077
std_ic_t2o_mou_9           7745    7.745077
loc_ic_t2f_mou_9           7745    7.745077
ic_others_9                7745    7.745077
loc_og_t2f_mou_9           7745    7.745077
loc_ic_t2m_mou_9           7745    7.745077
loc_og_t2c_mou_9           7745    7.745077
loc_og_t2m_mou_9           7745    7.745077
loc_ic_t2t_mou_9           7745    7.745077
loc_og_t2t_mou_9           7745    7.745077
std_ic_mou_9               7745    7.745077
std_og_t2t_mou_9           7745    7.745077
roam_og_mou_9              7745    7.745077
std_ic_t2t_mou_9           7745    7.745077
std_ic_t2f_mou_9           7745    7.745077
loc_og_mou_9               7745    7.745077
offnet_mou_9               7745    7.745077
std_og_t2m_mou_9           7745    7.745077
std_og_t2f_mou_9           7745    7.745077
std_og_t2c_mou_9           7745    7.745077
isd_og_mou_9               7745    7.745077
onnet_mou_9                7745    7.745077
std_og_mou_9               7745    7.745077
spl_og_mou_9               7745    7.745077
og_others_9                7745    7.745077
roam_ic_mou_9              7745    7.745077
std_ic_t2t_mou_8           5378    5.378054
offnet_mou_8               5378    5.378054
ic_others_8                5378    5.378054
isd_ic_mou_8               5378    5.378054
loc_ic_mou_8               5378    5.378054
std_og_t2c_mou_8           5378    5.378054
spl_ic_mou_8               5378    5.378054
og_others_8                5378    5.378054
loc_ic_t2f_mou_8           5378    5.378054
std_og_t2f_mou_8           5378    5.378054
loc_og_mou_8               5378    5.378054
std_ic_mou_8               5378    5.378054
std_ic_t2m_mou_8           5378    5.378054
std_og_t2m_mou_8           5378    5.378054
std_ic_t2o_mou_8           5378    5.378054
loc_og_t2c_mou_8           5378    5.378054
std_og_mou_8               5378    5.378054
std_ic_t2f_mou_8           5378    5.378054
roam_ic_mou_8              5378    5.378054
loc_og_t2t_mou_8           5378    5.378054
loc_ic_t2t_mou_8           5378    5.378054
roam_og_mou_8         

In [7]:
# Number of columns having null values
print(len(calnullpercentage(telecom)))

166


`Out of 226 columns 166 have null values`

In [8]:
#Checking categorical and numerical columns 
telecom.select_dtypes(include='object').head(3)

last_date_of_month_6 last_date_of_month_7 last_date_of_month_8  \
0            6/30/2014            7/31/2014            8/31/2014   
1            6/30/2014            7/31/2014            8/31/2014   
2            6/30/2014            7/31/2014            8/31/2014   

  last_date_of_month_9 date_of_last_rech_6 date_of_last_rech_7  \
0            9/30/2014           6/21/2014           7/16/2014   
1            9/30/2014           6/29/2014           7/31/2014   
2            9/30/2014           6/17/2014           7/24/2014   

  date_of_last_rech_8 date_of_last_rech_9 date_of_last_rech_data_6  \
0            8/8/2014           9/28/2014                6/21/2014   
1           8/28/2014           9/30/2014                      NaN   
2           8/14/2014           9/29/2014                      NaN   

  date_of_last_rech_data_7 date_of_last_rech_data_8 date_of_last_rech_data_9  
0                7/16/2014                 8/8/2014                      NaN  
1                7/25/2014                8/10/2014                      NaN  
2                      NaN                      NaN                9/17/2014

In [9]:
#Finding categorical columns where dtype is float but those columns are having 0 or 1 values only
catg= []
for col in telecom.columns:
    if len(telecom[col].unique())== 2 | 3:
        catg.append(col)
catg

['night_pck_user_6',
 'night_pck_user_7',
 'night_pck_user_8',
 'night_pck_user_9',
 'fb_user_6',
 'fb_user_7',
 'fb_user_8',
 'fb_user_9']

In [10]:
# Create a backup of data 
tlcom_df = telecom.copy()

In [11]:
#Columns Types

#id columns 
id_cols = ['mobile_number' , 'circle_id']
print("Id columns :\n", id_cols)
print('\n')


#date_cols
date_cols = list(telecom.select_dtypes(include='object').columns)
print("Date columns :\n", date_cols)

cat_cols = catg
print( "\nCategorical columns :\n" ,cat_cols)

#numeric cols
num_cols  = [col for col in telecom.columns if col not in id_cols + date_cols + cat_cols ]

# print the number of columns in each list
print("\n#ID cols: %d\n#Date cols:%d\n#Numeric cols:%d\n#Category cols:%d" % (len(id_cols), len(date_cols), len(num_cols), len(cat_cols)))

# check if we have missed any column
print( len(id_cols)+len(date_cols)+ len(num_cols)+len(cat_cols) == len(telecom.columns))

Id columns :
 ['mobile_number', 'circle_id']


Date columns :
 ['last_date_of_month_6', 'last_date_of_month_7', 'last_date_of_month_8', 'last_date_of_month_9', 'date_of_last_rech_6', 'date_of_last_rech_7', 'date_of_last_rech_8', 'date_of_last_rech_9', 'date_of_last_rech_data_6', 'date_of_last_rech_data_7', 'date_of_last_rech_data_8', 'date_of_last_rech_data_9']

Categorical columns :
 ['night_pck_user_6', 'night_pck_user_7', 'night_pck_user_8', 'night_pck_user_9', 'fb_user_6', 'fb_user_7', 'fb_user_8', 'fb_user_9']

#ID cols: 2
#Date cols:12
#Numeric cols:204
#Category cols:8
True


## Filter high-value customers
We need to predict churn only for the high-value customers. Define high-value customers as follows: Those who have recharged with an amount more than or equal to X, where X is the 70th percentile of the average recharge amount in the first two months (the good phase).

In [12]:
# Deriving new columns for total recharge amount data for 6 and 7th month
telecom['tot_av_rech_amt_data_6'] = telecom['total_rech_data_6'] * telecom['av_rech_amt_data_6']
telecom['tot_av_rech_amt_data_7'] = telecom['total_rech_data_7'] * telecom['av_rech_amt_data_7']
# Deriving new columns for total amount spent during  6 and 7th month
telecom['tot_amt_data_6'] = telecom[['total_rech_amt_6','tot_av_rech_amt_data_6']].sum(axis=1)
telecom['tot_amt_data_7'] = telecom[['total_rech_amt_7','tot_av_rech_amt_data_7']].sum(axis=1)
#first two months average
telecom['avg_amt_data_7'] = telecom[['tot_amt_data_6','tot_amt_data_7']].mean(axis=1)
# Filtering customers based on percentile having goodphase_avg more than or equal to cutoff of 70th percentile
telecom=telecom.loc[(telecom['avg_amt_data_7'] >= np.percentile(telecom['avg_amt_data_7'], 70))]
telecom.shape

(30001, 231)

` I have taken  recharge amount `more than or equal to X`, where X is the 70th percentile of the average recharge amount in the first two months and getting 30k rows. If I use `more than(>)sign`, will get 29.9k rows, but going with problem statement.`

In [13]:
# Deriving new columns for total recharge amount data for 8 and 9th month
telecom['tot_av_rech_amt_data_8'] = telecom['total_rech_data_8'] * telecom['av_rech_amt_data_8']
telecom['tot_av_rech_amt_data_9'] = telecom['total_rech_data_9'] * telecom['av_rech_amt_data_9']
# Deriving new columns for total amount spent during  8 and 9th month
telecom['tot_amt_data_8'] = telecom[['total_rech_amt_8','tot_av_rech_amt_data_8']].sum(axis=1)
telecom['tot_amt_data_9'] = telecom[['total_rech_amt_9','tot_av_rech_amt_data_9']].sum(axis=1)

#### Dropping Redundant columns, since we have already created derived features from them and derived features reflects the same information.

In [14]:
telecom.drop(['tot_av_rech_amt_data_6','tot_av_rech_amt_data_7','tot_av_rech_amt_data_8','tot_av_rech_amt_data_9'],inplace=True,axis=1)
